#!/usr/bin/env bash

IPGIVEN=${1?Error:NO IP GIVEN}
gst-launch-1.0 -v v4l2src device=/dev/video0 ! video/x-raw,format=YUY2,width=640,height=480,framerate=30/1 ! jpegenc ! rtpjpegpay ! udpsink host=$IPGIVEN port=5000
